# Generated by Django 3.1.7 on 2021-04-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0002_donate_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=25, max_digits=10),
        ),
    ]
