# Generated by Django 3.1.7 on 2021-08-11 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0003_auto_20210428_1849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donate',
            options={'verbose_name': 'Donation', 'verbose_name_plural': 'Donations'},
        ),
        migrations.AlterField(
            model_name='donate',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
