# Generated by Django 3.1.7 on 2021-04-13 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myaccount', '0007_auto_20210406_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='all_classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('class_subject', models.CharField(max_length=100)),
                ('class_university', models.CharField(max_length=100)),
                ('class_collage', models.CharField(max_length=100)),
                ('class_department', models.CharField(max_length=100)),
                ('class_level', models.CharField(max_length=100)),
                ('class_division', models.CharField(max_length=100)),
                ('class_year', models.CharField(max_length=100)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myaccount.useraccount')),
            ],
        ),
    ]
