# Generated by Django 3.1.7 on 2021-04-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myclasses', '0003_allmaterials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allclasses',
            name='class_collage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='allclasses',
            name='class_department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='allclasses',
            name='class_division',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='allclasses',
            name='class_university',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
