# Generated by Django 3.1.7 on 2021-04-21 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myclasses', '0004_auto_20210419_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='allmaterials',
            name='for_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myclasses.allclasses'),
            preserve_default=False,
        ),
    ]
