# Generated by Django 3.1.7 on 2021-04-22 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0008_auto_20210418_1921'),
        ('myclasses', '0005_allmaterials_for_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_code', models.CharField(max_length=100)),
                ('registered_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myclasses.allclasses')),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myaccount.useraccount')),
            ],
        ),
    ]
