# Generated by Django 3.1.7 on 2021-04-22 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myclasses', '0007_auto_20210422_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classregister',
            name='join_code',
            field=models.BooleanField(),
        ),
    ]
