# Generated by Django 3.1.7 on 2021-04-22 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myclasses', '0008_auto_20210422_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classregister',
            name='join_code',
            field=models.CharField(max_length=100),
        ),
    ]
