# Generated by Django 3.1.7 on 2021-04-23 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0008_auto_20210418_1921'),
        ('myclasses', '0009_auto_20210422_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classregister',
            name='student_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myaccount.useraccount'),
        ),
    ]
