# Generated by Django 3.1.7 on 2021-04-25 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myclasses', '0010_auto_20210423_0343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allclasses',
            options={'verbose_name': 'Class', 'verbose_name_plural': 'All Classes'},
        ),
        migrations.AlterModelOptions(
            name='allmaterials',
            options={'verbose_name': 'Matrial', 'verbose_name_plural': 'All Materials'},
        ),
        migrations.AlterModelOptions(
            name='classregister',
            options={'verbose_name': 'Class Register', 'verbose_name_plural': 'Class Register'},
        ),
    ]
