# Generated by Django 3.1.7 on 2021-04-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0007_auto_20210406_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='bio',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
