# Generated by Django 3.1.7 on 2021-04-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0008_auto_20210418_1921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccount',
            options={'verbose_name': 'User Account', 'verbose_name_plural': 'User Accounts'},
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='user_type',
            field=models.CharField(blank=True, choices=[('teacher', 'Teacher'), ('student', 'Student')], default='student', max_length=100, null=True),
        ),
    ]
